name: 'Setup Odin'
description: 'Setup the Odin compiler'
author: 'laytan'
branding:
  color: blue
  icon: code
inputs:
  odin-version:
    description: 'The Odin version to setup, supports tag names and branch names'
    default: 'master'
    required: true
  llvm-version:
    description: 'Which version of LLVM to install, supports 11, 12, 13 and 14, this option has no effect on Windows (14 is recommended as this is pre-installed by GitHub)'
    default: '14'
    required: true
  build-type:
    description: 'Type of Odin build, supports "debug", "release" or "release_native"'
    default: 'debug'
    required: true
  repository:
    description: 'The repository to pull Odin from'
    default: 'https://github.com/odin-lang/Odin'
    required: true
  cache:
    description: 'Enables caching the compiler binary, NOTE: this is probably slower than redownloading it everytime.'
    default: 'false'
outputs:
  cache-hit:
    description: 'A boolean value to indicate if a cache was hit'
runs:
  using: 'node20'
  main: 'dist/setup/index.js'
  post: 'dist/cache-save/index.js'
  post-if: success()
