name: "units-test"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-14] # macos-14 is an arm machine.
        # not doing 13 anymore, see Odin #4017
        llvm-version: [17, 18]
        build-type: [debug, release, release-native]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        llvm-version: ${{ matrix.llvm-version }}
        release: false
        build-type: ${{ matrix.build-type }}
    - name: Version
      run: odin version
    - name: Report
      run: odin report
    - name: Run test program
      run: odin run test.odin -file

  test-release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-14] # macos-14 is an arm machine.
        release: [latest, dev-2024-05, nightly]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        release: ${{ matrix.release }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Version
      run: odin version
    - name: Report
      run: odin report
    - name: Run test program
      run: odin run test.odin -file

  test-with-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-14] # macos-14 is an arm machine.
        odin-version: [master]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        branch: ${{ matrix.odin-version }}
        llvm-version: 17
        release: false
        cache: true
    - name: Version
      run: odin version
    - name: Report
      run: odin report
    - name: Run test program
      run: odin run test.odin -file

  test-auxiliary:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Version
        run: odin version
      - name: Report
        run: odin report
      - name: WASM
        run: odin build test.odin -file -target:js_wasm32
      - name: Get NASM
        run: sudo apt-get install -y nasm
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: ASM
        run: odin run test-minimal.odin -file -no-crt -default-to-nil-allocator -no-thread-local
        # See Odin #4016
        if: ${{ matrix.os != 'macos-14' && matrix.os != 'macos-latest' }}
