name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        llvm-version: [13, 14]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        llvm-version: ${{ matrix.llvm-version }}
        release: false
    - name: Version
      run: odin version
    - name: Report
      run: odin report
    - name: Run test program
      run: odin run test.odin -file

  test-release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        release: [latest, dev-2023-10]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        release: ${{ matrix.release }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Version
      run: odin version
    - name: Report
      run: odin report
    - name: Run test program
      run: odin run test.odin -file

  test-with-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        odin-version: [master, dev-2023-08]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        branch: ${{ matrix.odin-version }}
        llvm-version: 14
        release: false
    - name: Version
      run: odin version
    - name: Report
      run: odin report
    - name: Run test program
      run: odin run test.odin -file
