name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-14] # macos-14 is an arm machine.
        llvm-version: [13, 14]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        llvm-version: ${{ matrix.llvm-version }}
        release: false
    - name: Version
      run: odin version
    - name: Report
      run: odin report
    - name: Run test program
      run: odin run test.odin -file

  test-release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-14] # macos-14 is an arm machine.
        release: [latest, dev-2023-10]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        release: ${{ matrix.release }}
        token: ${{ secrets.GITHUB_TOKEN }}
        llvm-version: 13
    - name: Version
      run: odin version
    - name: Report
      run: odin report
    - name: Run test program
      run: odin run test.odin -file

  test-with-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-14] # macos-14 is an arm machine.
        odin-version: [master, dev-2023-08]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        branch: ${{ matrix.odin-version }}
        llvm-version: 14
        release: false
        cache: true
    - name: Version
      run: odin version
    - name: Report
      run: odin report
    - name: Run test program
      run: odin run test.odin -file

  test-source-llvm-17:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          release: false
          llvm-version: 17
      - name: Version
        run: odin version
      - name: Report
        run: odin report
      - name: Run test program
        run: odin run test.odin -file

  test-auxiliary:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Version
        run: odin version
      - name: Report
        run: odin report
      - name: WASM
        run: odin build test.odin -file -target:js_wasm32
        # See Odin #3396
        # - name: Get NASM
        #   run: sudo apt-get install -y nasm
        #   if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: ASM
        run: odin run test-minimal.odin -file -no-crt -default-to-nil-allocator -no-thread-local
        # See Odin #3396
        if: ${{ matrix.os != 'ubuntu-latest' }}
